### ISSUE TITLE
Error: ELOOP: too many symbolic links encountered

### ISSUE THREAD

**Issue by DuanPengfei** [yujintang/tree2#1]
在不附加 option 时会报错 `tree2 ./`

![image](https://cloud.githubusercontent.com/assets/4469502/24097334/4c59a6d6-0da0-11e7-9897-fd2cdce0b31f.png)

**Comment by yujintang** [comment]
这个应该是symbolic links 的问题，和options没关系的

**Comment by DuanPengfei** [comment]
知道是 symbolic links 的问题，不要解决一下？

**Comment by yujintang** [comment]
你下载一下最新版，最新版问题解决了.
